server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      default-filters:
        - name: CircuitBreaker
          args:
            name: default
            fallbackUri: forward:/fallback
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE
                methods: GET,POST
                backoff:
                  firstBackoff: 10ms
                  maxBackoff: 1000ms
                  factor: 2
                  basedOnPreviousValue: false